name: "Integration tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

jobs:
  TestWithoutProjectMining:
    runs-on: ubuntu-latest
    name: Integration Tests without project mining
    steps:
    - name: Checkout repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect data for Integration tests
      id: collect_data_without_project
      uses: AbsaOSS/living-doc-collector-gh@6baaa84604e8e48d2561eca027166d34d9043bf2
      env:
        GITHUB-TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
      with:
        doc-issues: true
        verbose-logging: true

        doc-issues-repositories: |
          [
            {
              "organization-name": "AbsaOSS",
              "repository-name": "living-doc-generator",
              "projects-title-filter": [] 
            }
          ]
        doc-issues-project-state-mining: false

    - name: Integration test
      id: generate_living_doc_1
      uses: ./
      with:
        source: "${{ steps.collect_data_without_project.outputs.output-path }}/doc-issues/doc-issues.json"
        report-page: true
        verbose-logging: true

    - name: Show generated output
      run: ls -lR "${{ steps.generate_living_doc_1.outputs.output-path }}"

    - name: Verify integration test results
      run: pytest tests/integration/validate_outputs_test.py::test_validate_for_test_without_project_mining

  TestsWithProjectMining:
    runs-on: ubuntu-latest
    name: Integration Tests with project mining
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect data with Project for Integration tests
        id: collect_data_with_project_1
        uses: AbsaOSS/living-doc-collector-gh@6baaa84604e8e48d2561eca027166d34d9043bf2
        env:
          GITHUB-TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
        with:
          doc-issues: true
          verbose-logging: true

          doc-issues-repositories: |
            [
              {
                "organization-name": "AbsaOSS",
                "repository-name": "living-doc-generator",
                "projects-title-filter": []
              }
            ]
          doc-issues-project-state-mining: true

      - name: Integration test
        id: generate_living_doc_1
        uses: ./
        env:
          GITHUB-TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
        with:
          source: "${{ steps.collect_data_with_project_1.outputs.output-path }}/doc-issues/doc-issues.json"
          report-page: true
          verbose-logging: true

      - name: Show generated output
        run: ls -lR "${{ steps.generate_living_doc_1.outputs.output-path }}"

      - name: Verify integration test results
        run: pytest tests/integration/validate_outputs_test.py::test_validate_for_test_with_project_mining

  TestWithProjectMiningExcludeProject:
    runs-on: ubuntu-latest
    name: Integration Tests with project mining and excluded project
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect data with Project for Integration tests
        id: collect_data_with_project_2
        uses: AbsaOSS/living-doc-collector-gh@6baaa84604e8e48d2561eca027166d34d9043bf2
        env:
          GITHUB-TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
        with:
          doc-issues: true
          verbose-logging: true

          doc-issues-repositories: |
            [
              {
                "organization-name": "AbsaOSS",
                "repository-name": "living-doc-generator",
                "projects-title-filter": []
              }
            ]
          doc-issues-project-state-mining: true

      - name: Integration test
        id: generate_living_doc_2
        uses: ./
        env:
          GITHUB-TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
        with:
          source: "${{ steps.collect_data_with_project_2.outputs.output-path }}/doc-issues/doc-issues.json"
          report-page: true
          verbose-logging: true

      - name: Show generated output
        run: ls -lR "${{ steps.generate_living_doc_2.outputs.output-path }}"

      - name: Verify integration test results
        run: pytest tests/integration/validate_outputs_test.py::test_validate_for_test_with_project_mining_and_excluded_project
